export const CategoryList=[  
   {"label": "All Courses","url":"AllCourses"},
   {"label": "Academics &Education","url":"academics%20%26%20education"},
   {"label": "Adult Content","url":"adult%20content"},
   {"label":  "Art & Design","url":"art%20%26%20design"},
   {"label": "Brodcasting","url":"broadcasting"},
   {"label": "Business","url":"business"},
   {"label": "Development","url":"development"},
   {"label": "Engineering","url":"engineering"},
   {"label": "Finance","url":"finance"},
   {"label":"Food & Nutrition","url":"food%20%26%20nutrition"},
   {"label": "Health & Fitness","url":"health%20%26%20fitness"},
   {"label": "Home & Gardening","url":"home%20%26%20gardening"},
   {"label": "IT & Software","url":"it%20%26%20software"},
   {"label": "Languages","url":"languages"},
   {"label": "Lifestyle","url":"lifestyle"},
   {"label": "Music & Dance","url":"music%20%26%20dance"},
   {"label": "Politics","url":"politics"},
   {"label": "Post Secondary","url":"post%20secondary"},
   {"label": "Sales & Marketing","url":"sales%20%26%20marketing"},
   {"label":"Sports","url":"sports"},
   {"label": "Style & Beauty","url":"style%20%26%20beauty"},
   {"label": "Uncategorized","url":"uncategorized"},
   {"label": "Video & Photography","url":"video%20%26%20photography"},
]